export default {
  STORE_SOMETHING: 'STORE_SOMETHING',
  CREATE_TRIP: 'CREATE_TRIP',
<<<<<<< HEAD
  CHECK_LOGIN: 'CHECK_LOGIN'  
=======
  GET_ALL_TRIPS: 'GET_ALL_TRIPS',
  SET_CURRENT_TRIP: 'SET_CURRENT_TRIP'  
>>>>>>> 03_HomePage
}
