export default {
  STORE_SOMETHING: 'STORE_SOMETHING',
  CREATE_TRIP: 'CREATE_TRIP',
  CHECK_LOGIN: 'CHECK_LOGIN',
  GET_ALL_TRIPS: 'GET_ALL_TRIPS',
  SET_CURRENT_TRIP: 'SET_CURRENT_TRIP',
  ADD_MEMBER: 'ADD_MEMBER',
  GET_TRIP_MEMBERS: 'GET_TRIP_MEMBERS'  
}
